"""Ported schema improvements

Revision ID: rel_003
Revises: rel_002
Create Date: 2026-02-12 12:00:00.000000

"""

from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "rel_003"
down_revision = "rel_002"
branch_labels = ("relationship",)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE contacts ADD COLUMN first_name TEXT")
    op.execute("ALTER TABLE contacts ADD COLUMN last_name TEXT")
    op.execute("ALTER TABLE contacts ADD COLUMN nickname TEXT")
    op.execute("ALTER TABLE contacts ADD COLUMN company TEXT")
    op.execute("ALTER TABLE contacts ADD COLUMN job_title TEXT")
    op.execute("ALTER TABLE contacts ADD COLUMN gender TEXT")
    op.execute("ALTER TABLE contacts ADD COLUMN pronouns TEXT")
    op.execute("ALTER TABLE contacts ADD COLUMN avatar_url TEXT")
    op.execute("ALTER TABLE contacts ADD COLUMN listed BOOLEAN DEFAULT true")
    op.execute("ALTER TABLE contacts ADD COLUMN metadata JSONB DEFAULT '{}'")
    op.execute("ALTER TABLE contacts DROP COLUMN name")
    op.execute("ALTER TABLE contacts DROP COLUMN details")
    op.execute("ALTER TABLE contacts DROP COLUMN archived_at")

    op.execute("ALTER TABLE notes ADD COLUMN title TEXT")
    op.execute("ALTER TABLE notes RENAME COLUMN content TO body")

    op.execute("ALTER TABLE reminders ADD COLUMN label TEXT")
    op.execute("ALTER TABLE reminders ADD COLUMN type TEXT")
    op.execute("ALTER TABLE reminders ADD COLUMN next_trigger_at TIMESTAMPTZ")
    op.execute("ALTER TABLE reminders ADD COLUMN last_triggered_at TIMESTAMPTZ")
    op.execute("ALTER TABLE reminders DROP COLUMN message")
    op.execute("ALTER TABLE reminders DROP COLUMN reminder_type")
    op.execute("ALTER TABLE reminders DROP COLUMN cron")
    op.execute("ALTER TABLE reminders DROP COLUMN due_at")
    op.execute("ALTER TABLE reminders DROP COLUMN dismissed")

    op.execute("ALTER TABLE loans ADD COLUMN lender_contact_id UUID REFERENCES contacts(id)")
    op.execute("ALTER TABLE loans ADD COLUMN borrower_contact_id UUID REFERENCES contacts(id)")
    op.execute("ALTER TABLE loans ADD COLUMN name TEXT")
    op.execute("ALTER TABLE loans ADD COLUMN amount_cents INTEGER")
    op.execute("ALTER TABLE loans ADD COLUMN currency TEXT")
    op.execute("ALTER TABLE loans DROP COLUMN contact_id")
    op.execute("ALTER TABLE loans DROP COLUMN amount")
    op.execute("ALTER TABLE loans DROP COLUMN direction")
    op.execute("ALTER TABLE loans DROP COLUMN description")

    op.execute("ALTER TABLE groups ADD COLUMN type TEXT")
    op.execute("ALTER TABLE group_members ADD COLUMN role TEXT")

    op.execute("ALTER TABLE activity_feed ADD COLUMN entity_type TEXT")
    op.execute("ALTER TABLE activity_feed ADD COLUMN entity_id UUID")
    op.execute("ALTER TABLE activity_feed RENAME COLUMN type TO action")
    op.execute("ALTER TABLE activity_feed RENAME COLUMN description TO summary")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE contacts DROP COLUMN first_name")
    op.execute("ALTER TABLE contacts DROP COLUMN last_name")
    op.execute("ALTER TABLE contacts DROP COLUMN nickname")
    op.execute("ALTER TABLE contacts DROP COLUMN company")
    op.execute("ALTER TABLE contacts DROP COLUMN job_title")
    op.execute("ALTER TABLE contacts DROP COLUMN gender")
    op.execute("ALTER TABLE contacts DROP COLUMN pronouns")
    op.execute("ALTER TABLE contacts DROP COLUMN avatar_url")
    op.execute("ALTER TABLE contacts DROP COLUMN listed")
    op.execute("ALTER TABLE contacts DROP COLUMN metadata")
    op.execute("ALTER TABLE contacts ADD COLUMN name TEXT")
    op.execute("ALTER TABLE contacts ADD COLUMN details JSONB")
    op.execute("ALTER TABLE contacts ADD COLUMN archived_at TIMESTAMPTZ")

    op.execute("ALTER TABLE notes DROP COLUMN title")
    op.execute("ALTER TABLE notes RENAME COLUMN body TO content")

    op.execute("ALTER TABLE reminders DROP COLUMN label")
    op.execute("ALTER TABLE reminders DROP COLUMN type")
    op.execute("ALTER TABLE reminders DROP COLUMN next_trigger_at")
    op.execute("ALTER TABLE reminders DROP COLUMN last_triggered_at")
    op.execute("ALTER TABLE reminders ADD COLUMN message TEXT")
    op.execute("ALTER TABLE reminders ADD COLUMN reminder_type TEXT")
    op.execute("ALTER TABLE reminders ADD COLUMN cron TEXT")
    op.execute("ALTER TABLE reminders ADD COLUMN due_at TIMESTAMPTZ")
    op.execute("ALTER TABLE reminders ADD COLUMN dismissed BOOLEAN")

    op.execute("ALTER TABLE loans DROP COLUMN lender_contact_id")
    op.execute("ALTER TABLE loans DROP COLUMN borrower_contact_id")
    op.execute("ALTER TABLE loans DROP COLUMN name")
    op.execute("ALTER TABLE loans DROP COLUMN amount_cents")
    op.execute("ALTER TABLE loans DROP COLUMN currency")
    op.execute("ALTER TABLE loans ADD COLUMN contact_id UUID")
    op.execute("ALTER TABLE loans ADD COLUMN amount NUMERIC")
    op.execute("ALTER TABLE loans ADD COLUMN direction TEXT")
    op.execute("ALTER TABLE loans ADD COLUMN description TEXT")

    op.execute("ALTER TABLE groups DROP COLUMN type")
    op.execute("ALTER TABLE group_members DROP COLUMN role")

    op.execute("ALTER TABLE activity_feed DROP COLUMN entity_type")
    op.execute("ALTER TABLE activity_feed DROP COLUMN entity_id")
    op.execute("ALTER TABLE activity_feed RENAME COLUMN action TO type")
    op.execute("ALTER TABLE activity_feed RENAME COLUMN summary TO description")
    # ### end Alembic commands ###
