"""tombstone_memory_calendar_episodes

Revision ID: chronicler_008
Revises: chronicler_007
Create Date: 2026-04-30 00:00:00.000000

Idempotent data migration that tombstones pre-existing
``chronicler.episodes`` rows produced from butler-managed memory
scheduled tasks that were incorrectly projected as calendar events.

Background
----------
Before bu-daaff (PR #1297), the CalendarCompletedAdapter projected ALL
completed calendar event instances — including instances generated by
butler-internal memory housekeeping tasks such as
``memory_consolidation``, ``memory_episode_cleanup``, and
``memory_purge_superseded``.  These rows carry no "lived past time"
signal and pollute the Calendar lane in the Chronicler dashboard.

bu-daaff shipped two prevention tracks so *future* rows are clean:
  - Track A: ``WHERE dispatch_mode != 'job'`` in
    ``src/butlers/modules/calendar.py:_project_scheduler_source()`` —
    memory housekeeping tasks use ``dispatch_mode='job'`` and are now
    excluded from scheduler-source projection.
  - Track B: ``INNER JOIN calendar_sources WHERE cs.lane != 'butler'``
    in ``src/butlers/chronicler/adapters/calendar.py`` —
    CalendarCompletedAdapter rejects any instance whose calendar source
    is marked as a butler-internal lane.

Neither track retroactively cleans existing rows.  This migration
handles the historical backfill so that environments self-heal on first
Chronicler boot after bu-daaff: it sets ``tombstone_at = now()`` and
``tombstone_reason`` on any remaining episode row produced from the
known butler-managed memory task names.

Dependency
----------
This migration **requires chronicler_007 to have run first**.
chronicler_007 (bu-6t63s, PR #1299) adds the ``tombstone_reason``
column to ``episodes`` and ``point_events``.  If chronicler_007 has
not yet merged into main when this migration runs, Alembic will refuse
to apply it (the ``down_revision`` guard enforces ordering).

Filter design
-------------
Two design options were considered:

  Option A — ``title LIKE 'memory_%'``
    Simple pattern, but ``memory_%`` would catch any calendar event
    whose title happens to start with "memory" — including legitimate
    user events like "Memory workshop" or "Memory palace tour".

  Option B — exact IN list ('memory_consolidation', 'memory_episode_cleanup',
             'memory_purge_superseded')
    Requires knowing the full name set, but is safe and scoped precisely
    to the three known butler-managed task names documented in the issue.

**Option B (exact list) is used here** for safety.  A user calendar
event titled "memory_consolidation" is improbable, but the tombstone
mutation is irreversible within a migration run, so precision is worth
the verbosity.

If additional memory task names are identified, a new migration should
be created with the extended list rather than modifying this one.

Idempotency
-----------
The ``tombstone_at IS NULL`` guard in the WHERE clause ensures that
re-running this migration touches zero additional rows.

Downgrade
---------
Downgrade is a no-op: tombstones are not reversed on downgrade.
Removing a tombstone could re-surface rows the user never saw and
create confusing artefacts.

Issue: bu-aqqx0
Siblings: bu-daaff (prevention tracks), bu-6t63s (chronicler_007 + tombstone_reason column)
"""

from __future__ import annotations

import logging

from alembic import op

# revision identifiers, used by Alembic.
revision = "chronicler_008"
down_revision = "chronicler_007"
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)

# The source name used by CalendarCompletedAdapter.
# Constant from src/butlers/chronicler/adapters/calendar.py:SOURCE_NAME
_SOURCE_NAME = "google_calendar.completed"

# Exact set of known butler-managed memory task titles to tombstone.
# These are the three memory housekeeping jobs that were incorrectly
# projected as calendar events before bu-daaff. See docstring for the
# rationale behind using an exact list instead of LIKE 'memory_%'.
_BUTLER_MEMORY_TASK_TITLES: tuple[str, ...] = (
    "memory_consolidation",
    "memory_episode_cleanup",
    "memory_purge_superseded",
)

_TOMBSTONE_REASON = "butler-managed calendar event retroactively excluded (bu-daaff+bu-aqqx0)"


def upgrade() -> None:
    # Build the IN-list literal for the exact-match set so we can embed it
    # in the SQL string (Alembic's op.execute does not accept bind params).
    in_list = ", ".join(f"'{title}'" for title in sorted(_BUTLER_MEMORY_TASK_TITLES))

    # Log per-title counts before applying so operators can see what was
    # backfilled in the migration log.
    _log_candidate_counts(in_list)

    op.execute(f"""
        UPDATE episodes
        SET tombstone_at    = now(),
            tombstone_reason = '{_TOMBSTONE_REASON}'
        WHERE source_name = '{_SOURCE_NAME}'
          AND tombstone_at IS NULL
          AND title IN ({in_list})
    """)


def downgrade() -> None:
    # Tombstones are NOT reversed on downgrade — reversing a tombstone could
    # silently re-surface rows the user has never seen.
    pass


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _log_candidate_counts(in_list: str) -> None:
    """Log per-title counts of not-yet-tombstoned memory calendar episodes.

    This function runs inside the migration context and uses op.get_bind()
    to read from the DB before the UPDATE is applied.  The counts are purely
    diagnostic; failures here do not abort the migration.
    """
    try:
        bind = op.get_bind()
        rows = bind.execute(
            __import__("sqlalchemy").text(f"""
                SELECT
                    title,
                    COUNT(*)::int AS n
                FROM episodes
                WHERE source_name = '{_SOURCE_NAME}'
                  AND tombstone_at IS NULL
                  AND title IN ({in_list})
                GROUP BY title
                ORDER BY title
            """)
        ).fetchall()

        total = 0
        for row in rows:
            title = row[0] or ""
            count = row[1]
            total += count
            logger.info(
                "chronicler_008: tombstone candidate — title=%r count=%d",
                title,
                count,
            )
        logger.info("chronicler_008: total tombstone candidates = %d", total)
    except Exception:
        logger.warning(
            "chronicler_008: could not collect candidate counts (non-fatal)",
            exc_info=True,
        )
