// Connector data — extends the connector list with auth state, health,
// recent throughput, sparkline, last-error, and per-kind config. Used by
// every Connectors / detail proposal.
//
// The shape leans into the Dispatch language: every field is *a fact*, not
// a label. No colors or icons live in here.

window.CONNECTOR_DETAILS = [
  {
    id: 'home_assistant',
    label: 'Home Assistant',
    kind: 'webhook',
    glyph: 'H',
    description: 'Local-network webhook bridge — sensors, presence, automations.',
    auth: { status: 'ok', note: 'long-lived token · rotated 12d ago', expires: '364d' },
    health: 'ok',
    lastEventAt: '11:32:54',
    events24h: 4128,
    rate1h: 142,  // events / hr
    sessions24h: 0,
    cost24h: 0,
    spark24h: [120, 88, 64, 22, 14, 8, 18, 42, 88, 124, 162, 188, 196, 210, 188, 162, 144, 121, 130, 168, 188, 158, 124, 142],
    filtered24h: 3204, // most HA traffic is preserved-only, never routed
    routedPct: 22,
    enabled: true,
    config: { endpoint: 'wss://ha.parrot-hen.ts.net/api/websocket', cadence: 'event-driven', latencyMs: 14 },
    scopes: ['states:read', 'states:subscribe', 'events:subscribe'],
    note: 'high-volume signal; most events stored without dispatch.',
  },
  {
    id: 'email',
    label: 'Email',
    kind: 'imap',
    glyph: 'E',
    description: 'IMAP IDLE on the personal mailbox. Drafts go to the outbox folder.',
    auth: { status: 'ok', note: 'app-password · gmail', expires: null },
    health: 'ok',
    lastEventAt: '10:10:47',
    events24h: 38,
    rate1h: 3,
    sessions24h: 18,
    cost24h: 0.094,
    spark24h: [0, 0, 1, 2, 0, 0, 1, 3, 4, 5, 4, 2, 3, 2, 1, 2, 2, 1, 3, 4, 2, 1, 0, 1],
    filtered24h: 4,
    routedPct: 89,
    enabled: true,
    config: { endpoint: 'imap.gmail.com:993', cadence: 'IDLE · 30s heartbeat', latencyMs: 220 },
    scopes: ['INBOX', 'Outbox/butlers'],
    incidents: [
      { ts: '09:31:07', kind: 'replay_pending', text: 'pdf.parse failed on encrypted attachment — British Gas statement' },
    ],
    note: '1 message needs replay.',
  },
  {
    id: 'telegram',
    label: 'Telegram',
    kind: 'long-poll',
    glyph: 'T',
    description: 'Bot relay via long-poll. Routes messages from approved contacts to relationship.',
    auth: { status: 'ok', note: 'bot token · @house_butler', expires: null },
    health: 'ok',
    lastEventAt: '11:18:02',
    events24h: 24,
    rate1h: 4,
    sessions24h: 41,
    cost24h: 0.0142,
    spark24h: [0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 3, 4, 3, 2, 1, 0, 0, 0, 1, 1, 0, 4],
    filtered24h: 0,
    routedPct: 100,
    enabled: true,
    config: { endpoint: 'api.telegram.org/getUpdates', cadence: 'long-poll · 30s', latencyMs: 480 },
    scopes: ['messages:read', 'contacts:approved-only'],
    note: 'priority tier — fast path.',
  },
  {
    id: 'whatsapp',
    label: 'WhatsApp',
    kind: 'webhook',
    glyph: 'W',
    description: 'Business-API webhook. Heavily filtered — groups default off.',
    auth: { status: 'ok', note: 'meta business app · cred ok', expires: '47d' },
    health: 'ok',
    lastEventAt: '11:14:48',
    events24h: 188,
    rate1h: 38,
    sessions24h: 6,
    cost24h: 0.0042,
    spark24h: [2, 1, 0, 0, 0, 0, 1, 8, 14, 22, 28, 34, 38, 42, 38, 30, 24, 18, 14, 10, 6, 4, 2, 1],
    filtered24h: 168,
    routedPct: 11,
    enabled: true,
    config: { endpoint: '/wh/whatsapp', cadence: 'event-driven', latencyMs: 32 },
    scopes: ['messages:read', 'contacts:basic'],
    note: 'group "Climbing crew" is filtered as low-signal.',
  },
  {
    id: 'spotify',
    label: 'Spotify',
    kind: 'poll',
    glyph: 'S',
    description: 'Listening-history poll for chronicler.',
    auth: { status: 'needs_reauth', note: 'scope `user-read-recently-played` rotated upstream', expires: 'now' },
    health: 'degraded',
    lastEventAt: '11:30:11',
    events24h: 142,
    rate1h: 18,
    sessions24h: 142,
    cost24h: 0.0298,
    spark24h: [4, 6, 8, 12, 14, 16, 18, 22, 20, 14, 12, 16, 22, 24, 20, 18, 14, 10, 12, 16, 18, 14, 10, 18],
    filtered24h: 0,
    routedPct: 100,
    enabled: true,
    config: { endpoint: '/me/player/recently-played', cadence: 'poll · 10m', latencyMs: 220 },
    scopes: ['user-read-recently-played', 'user-read-playback-state', 'user-top-read'],
    incidents: [
      { ts: '14:14', kind: 'qa.flag', text: 'patrol cycle 217 · failure_streak crossed 4' },
      { ts: '14:30', kind: 'error', text: 'ingest.spotify 401 scope_mismatch — 4 consecutive' },
      { ts: '14:32', kind: 'qa.alert', text: 'chronicler ingestion stalled — reauth needed' },
    ],
    note: 'reauth required — scope drift detected by qa.',
  },
  {
    id: 'calendar',
    label: 'Google Calendar',
    kind: 'webhook',
    glyph: 'K',
    description: 'Push-channel webhook for the primary calendar.',
    auth: { status: 'expiring', note: 'oauth refresh · channel expires in 4d', expires: '4d' },
    health: 'ok',
    lastEventAt: '08:14:50',
    events24h: 6,
    rate1h: 1,
    sessions24h: 12,
    cost24h: 0.0091,
    spark24h: [0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
    filtered24h: 0,
    routedPct: 100,
    enabled: true,
    config: { endpoint: '/wh/gcal/primary', cadence: 'webhook · 7d ttl', latencyMs: 240 },
    scopes: ['calendar.events.readonly', 'calendar.readonly'],
    note: 'channel renewal due Sunday.',
  },
  {
    id: 'notion',
    label: 'Notion',
    kind: 'poll',
    glyph: 'N',
    description: 'Polls workspace pages for diff-based chronicler ingestion.',
    auth: { status: 'ok', note: 'integration token · workspace owner', expires: null },
    health: 'ok',
    lastEventAt: '07:42:18',
    events24h: 12,
    rate1h: 0,
    sessions24h: 12,
    cost24h: 0.0108,
    spark24h: [0, 0, 0, 0, 0, 0, 1, 4, 2, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1],
    filtered24h: 0,
    routedPct: 100,
    enabled: true,
    config: { endpoint: 'api.notion.com/v1/search', cadence: 'poll · 30m', latencyMs: 320 },
    scopes: ['pages:read', 'databases:read'],
    incidents: [
      { ts: '07:30:14', kind: 'warning', text: 'rate-limited · backoff 4× applied · resolved' },
    ],
    note: 'rate-limit auto-resolved this morning.',
  },
  // Dormant / available
  {
    id: 'github',
    label: 'GitHub',
    kind: 'webhook',
    glyph: 'G',
    description: 'PR and issue activity for personal repos.',
    auth: { status: 'unconfigured', note: 'not connected', expires: null },
    health: 'off',
    lastEventAt: null,
    events24h: 0,
    rate1h: 0,
    sessions24h: 0,
    cost24h: 0,
    spark24h: Array(24).fill(0),
    filtered24h: 0,
    routedPct: null,
    enabled: false,
    config: null,
    scopes: [],
    note: 'available — not connected.',
  },
];

// ─── Filter / routing rules ──────────────────────────────────────────────
// Each rule explains why an event was kept, dropped, or fast-tracked. Rules
// have an order (first match wins for `tier`; multiple `filter` rules can
// stack). Counts are 24h matches.
window.INGESTION_RULES = [
  {
    id: 'r-priority-contacts',
    name: 'Priority contacts',
    note: 'Messages from people in the priority list bypass batching.',
    when: 'channel ∈ {telegram, whatsapp, email}  ·  sender ∈ contacts.priority',
    action: 'tier := priority',
    matches24h: 12,
    enabled: true,
    owner: 'system',
    examples: ['Mom · Telegram', 'Wei · Telegram', 'maya@hello.io · Calendar invite'],
  },
  {
    id: 'r-groups-lowsignal',
    name: 'Low-signal groups',
    note: 'Drop WhatsApp groups marked low-signal unless tagged @house.',
    when: 'channel = whatsapp  ·  kind = group.message  ·  group ∈ filters.lowsignal',
    action: 'drop  ·  preserve for replay',
    matches24h: 168,
    enabled: true,
    owner: 'tze',
    examples: ['"Climbing crew" · 142 msgs', '"Family chat" · 26 msgs'],
  },
  {
    id: 'r-ha-presence-delta',
    name: 'HA presence — delta only',
    note: 'Store presence sensor state changes; don\'t dispatch unless co-occurring with another signal within 90s.',
    when: 'channel = home_assistant  ·  entity ~ binary_sensor.presence_*',
    action: 'preserve  ·  no dispatch',
    matches24h: 2188,
    enabled: true,
    owner: 'system',
    examples: ['fp2 · 8b1c · 1144 deltas', 'living room · 612 deltas'],
  },
  {
    id: 'r-ha-air-quality',
    name: 'HA air-quality',
    note: 'VOC / CO₂ deltas under 30ppb dropped as noise.',
    when: 'channel = home_assistant  ·  entity ~ sensor.*_air_monitor_*  ·  delta < 30',
    action: 'drop',
    matches24h: 1016,
    enabled: true,
    owner: 'tze',
    examples: ['bedroom · voc · 802 dropped', 'kitchen · co2 · 214 dropped'],
  },
  {
    id: 'r-spotify-skip',
    name: 'Spotify — skips',
    note: 'Tracks played < 30s are dropped; chronicler only cares about full listens.',
    when: 'channel = spotify  ·  kind = play.recent  ·  duration_played_ms < 30000',
    action: 'drop',
    matches24h: 22,
    enabled: true,
    owner: 'tze',
    examples: ['Tycho — "Awake" · 12s', 'Burial — "Antarctica" · 4s'],
  },
  {
    id: 'r-email-newsletters',
    name: 'Email newsletters',
    note: 'Marketing / list-unsubscribe-bearing email routes only to chronicler.',
    when: 'channel = email  ·  headers.list-unsubscribe?',
    action: 'route := chronicler',
    matches24h: 18,
    enabled: true,
    owner: 'system',
    examples: ['Chelsea / IFTTT', 'Stripe Atlas', 'Linear weekly'],
  },
  {
    id: 'r-billing-priority',
    name: 'Billing priority',
    note: 'Statements and invoices route to household.',
    when: 'channel = email  ·  subject ~ /statement|invoice|bill/i',
    action: 'route := household',
    matches24h: 4,
    enabled: true,
    owner: 'system',
    examples: ['British Gas · April', 'Octopus · April', 'Stripe · receipt'],
  },
  {
    id: 'r-notion-daily-log',
    name: 'Notion · daily log',
    note: 'Diffs of the daily-log page only — chronicler subscribes.',
    when: 'channel = notion  ·  page.id = "daily-log"',
    action: 'route := chronicler',
    matches24h: 12,
    enabled: true,
    owner: 'tze',
    examples: ['07:42 · 4 blocks', 'yesterday 21:14 · 11 blocks'],
  },
  // Disabled / archived rule kept for reference
  {
    id: 'r-archived-zwave',
    name: 'Z-wave bridge',
    note: 'Old bridge — migrated to Home Assistant in March.',
    when: 'channel = zwave',
    action: 'drop',
    matches24h: 0,
    enabled: false,
    owner: 'tze',
    examples: [],
  },
];

// ─── Pipeline stats (24h) ────────────────────────────────────────────────
// Five gates between arrival and execution. Numbers are 24h totals;
// `drop` lines record events that left the pipeline at this stage.
window.PIPELINE_STATS = {
  window: '24h',
  total_received: 4572,
  stages: [
    {
      key: 'accept',
      label: 'accept',
      gloss: 'Connector decides whether to let the event in at all.',
      in: 4572,
      out: 4404,
      drops: [
        { count: 142, label: '"Climbing crew" WhatsApp group', rule: 'r-groups-lowsignal' },
        { count: 26,  label: 'low-delta VOC / CO₂ readings',    rule: 'r-ha-air-quality' },
      ],
    },
    {
      key: 'dedupe',
      label: 'dedupe',
      gloss: 'Identical events arriving from multiple sources are collapsed.',
      in: 4404,
      out: 4382,
      drops: [
        { count: 18, label: 'glucose · libre3 / healthkit mirror', rule: 'canonicalize-source' },
        { count:  4, label: 'webhook double-fires (HA)',           rule: 'event-id-dedupe' },
      ],
    },
    {
      key: 'tier',
      label: 'tier',
      gloss: 'Priority senders bypass batching; everything else is default tier.',
      in: 4382,
      out: 4382,
      tiered: { priority: 12, default: 4370 },
      drops: [],
    },
    {
      key: 'route',
      label: 'route',
      gloss: 'Either a butler subscribes (and a session opens) — or the event is preserved without dispatch.',
      in: 4382,
      out: 178,
      preserved: 4204,
      drops: [],
    },
    {
      key: 'execute',
      label: 'execute',
      gloss: 'Butlers run. Failures are queued for replay; the human is notified only on hard errors.',
      in: 178,
      out: 177,
      executed: { ok: 177, replay_pending: 1, errored: 0 },
      drops: [],
    },
  ],
};

// ─── Priority contacts ──────────────────────────────────────────────────
// First-class list of "people who matter" — they bypass the default tier
// and notify their assigned butler immediately. This is data, not a rule.
window.PRIORITY_CONTACTS = [
  { name: 'Mom',     handle: '@meiying.parent', channel: 'telegram', butler: 'relationship', added: '12 Nov 2024', lastSeen: '09:54' },
  { name: 'Wei',     handle: '@weiminator',     channel: 'telegram', butler: 'relationship', added: '8 Feb 2025',  lastSeen: '11:18' },
  { name: 'Maya',    handle: 'maya@hello.io',   channel: 'email',    butler: 'relationship', added: '19 Aug 2024', lastSeen: '08:14' },
  { name: 'Dr. Patel', handle: 'patel@clinic.uk',  channel: 'email',    butler: 'health',       added: '22 Mar 2025', lastSeen: '3d ago' },
  { name: 'Chen-han', handle: '+44 7700 ...',    channel: 'whatsapp', butler: 'relationship', added: '4 Apr 2024',  lastSeen: '1h ago' },
];

// ─── Per-channel acceptance defaults ────────────────────────────────────
// What the channel does with an unmatched event by default.
window.CHANNEL_DEFAULTS = [
  { channel: 'home_assistant', policy: 'preserve · no dispatch',  note: 'high-volume; dispatch only when a rule routes it.' },
  { channel: 'email',          policy: 'route · switchboard',     note: 'switchboard classifies, then forwards.' },
  { channel: 'telegram',       policy: 'route · switchboard',     note: 'priority-tier for approved contacts.' },
  { channel: 'whatsapp',       policy: 'route · switchboard',     note: 'groups default-off (see filters).' },
  { channel: 'spotify',        policy: 'route · chronicler',      note: 'every full play; skips dropped.' },
  { channel: 'calendar',       policy: 'route · calendar + relationship', note: 'calendar reconciles; relationship logs touchpoints.' },
  { channel: 'notion',         policy: 'route · chronicler',      note: 'daily-log only; other pages preserved.' },
];

// Aggregate over 24h
window.RULES_TOTALS = (rules) => {
  const enabled = rules.filter((r) => r.enabled);
  return {
    rules: rules.length,
    active: enabled.length,
    matched: enabled.reduce((s, r) => s + r.matches24h, 0),
    routed:  enabled.filter((r) => r.action.startsWith('route')).reduce((s, r) => s + r.matches24h, 0),
    dropped: enabled.filter((r) => r.action.startsWith('drop')).reduce((s, r) => s + r.matches24h, 0),
  };
};
