/**
 * Public API surface — re-exports from client and types.
 */

export {
  ApiError,
  apiFetch,
  disconnectAccount,
  disconnectGoogleHealth,
  getAccountStatus,
  getGoogleAccounts,
  getGoogleCredentialStatus,
  getGoogleHealthStatus,
  getGoogleOAuthStartUrl,
  GOOGLE_HEALTH_SCOPES,
  setPrimaryAccount,
  upsertGoogleCredentials,
  createButlerSchedule,
  deleteButlerSchedule,
  getAuditLog,
  deleteButlerState,
  getButler,
  getButlerConfig,
  getButlerModules,
  getButlerLogs,
  getButlerMcpTools,
  getButlerNotifications,
  getButlerSchedules,
  getButlerSessions,
  getButlerSkills,
  getButlerState,
  getButlers,
  getButlersBoard,
  getConditions,
  createCondition,
  updateCondition,
  acceptCalendarProposal,
  deleteCondition,
  dismissCalendarProposal,
  getCalendarAccounts,
  getCalendarDayBriefing,
  getCalendarMeetingPrep,
  getCalendarWorkspace,
  getCalendarWorkspaceAudit,
  getCalendarWorkspaceEntry,
  getCalendarWorkspaceMeta,
  getCalendarWorkspaceDuplicates,
  getCalendarWorkspaceConflicts,
  patchCalendarDedupRules,
  setCalendarKeepSeparate,
  searchCalendarWorkspace,
  toggleCalendarSource,
  findCalendarWorkspaceTime,
  mutateCalendarWorkspaceButlerEvent,
  previewCalendarWorkspaceButlerEvent,
  mutateCalendarWorkspaceUserEvent,
  undoCalendarWorkspaceMutation,
  parseCalendarQuickAdd,
  getCostSummary,
  getDailyCosts,
  createEntityInfo,
  getEntities,
  getEntity,
  archiveEntity,
  promoteEntity,
  revealEntitySecret,
  setEntityLinkedContact,
  unlinkEntityContact,
  updateEntity,
  listRelationshipEntities,
  getRelationshipEntityQueue,
  archiveRelationshipEntity,
  dismissRelationshipEntityQueueItem,
  mergeRelationshipEntities,
  compareRelationshipEntities,
  dismissRelationshipEntityPair,
  promoteRelationshipEntity,
  createRelationshipEntity,
  getEntityLinkedContacts,
  addEntityContact,
  deleteEntityContact,
  markEntityContactVerified,
  updateEntityContact,
  setEntityPreferredChannel,
  clearEntityPreferredChannel,
  getEntityGifts,
  getEntityLoans,
  getEntityTimeline,
  getEntityMessageThreads,
  getEntityActivityBins,
  getEntityDeltaFacts,
  markEntityView,
  getEntityCoreDates,
  getEntityNeighbours,
  getPlexHalo,
  getEntityFacts,
  getEntityConcentration,
  updateEntityDunbarTier,
  forgetRelationshipEntity,
  confirmFact,
  retractFact,
  getEpisode,
  getEpisodes,
  getFact,
  getFacts,
  getHealth,
  getIssues,
  getIssueOccurrences,
  dismissIssue,
  undismissIssue,
  getMemoryActivity,
  getMemoryCompactionLog,
  getMemoryRetentionPolicies,
  getMemoryStats,
  getReembedPending,
  inspectMemory,
  runReembed,
  updateMemoryRetentionPolicies,
  getMeals,
  createMeal,
  updateMeal,
  deleteMeal,
  getNutritionSummary,
  getMeasurements,
  createMeasurement,
  updateMeasurement,
  deleteMeasurement,
  getMeasurementsLatest,
  getMeasurementSources,
  getMeasurementsTrend,
  getHealthBriefing,
  getInsightCandidates,
  getMedications,
  getMedicationDoses,
  getMedicationAdherence,
  logMedicationDose,
  createMedication,
  updateMedication,
  deleteMedication,
  getSleepLatest,
  getNotifications,
  getNotificationStats,
  markNotificationRead,
  acknowledgeAllFailed,
  getAttentionLedgerSummary,
  getResearch,
  createResearch,
  updateResearch,
  deleteResearch,
  getRule,
  getRules,
  getRegistry,
  getRoutingLog,
  setButlerEligibility,
  getSession,
  getSessions,
  getSessionAggregate,
  getSymptoms,
  createSymptom,
  updateSymptom,
  deleteSymptom,
  getTimeline,
  getTopSessions,
  getCostsBySchedule,
  getDispatchAttempts,
  searchAll,
  getContact,
  getContacts,
  patchContact,
  getOwnerSetupStatus,
  getGroup,
  getGroupMembers,
  getGroups,
  getLabels,
  createLabel,
  assignGroupLabel,
  removeGroupLabel,
  getUpcomingDates,
  getContactInteractions,
  getOverdueContacts,
  setButlerState,
  toggleButlerSchedule,
  triggerButler,
  forceButlerTick,
  triggerButlerSchedule,
  callButlerMcpTool,
  updateButlerSchedule,
  approveApproval,
  confirmAutonomySuggestion,
  createApprovalRule,
  createApprovalRuleFromAction,
  deferApproval,
  denyApproval,
  dismissAutonomySuggestion,
  getRulePromotionSuggestions,
  getRulePromotionStats,
  confirmRulePromotionSuggestion,
  dismissRulePromotionSuggestion,
  setRulePromotionRuleEnabled,
  getApprovalActions,
  getApprovalDetail,
  getApprovalGatedTools,
  getApprovalMetrics,
  getApprovalRuleSuggestions,
  getApprovalRules,
  getApprovalsFlat,
  getApprovalsHistory,
  getApprovalsPolicy,
  updateApprovalsPolicy,
  getGeneralSettings,
  getAutonomySuggestions,
  retryApproval,
  revokeApprovalRule,
  setPrimaryCalendar,
  syncCalendarWorkspace,
  getHomeSnapshotStatus,
  getHomeDevices,
  getHomeMaintenance,
  getHomeEnergy,
  getHomeEnergyTopConsumers,
  getHomeCommandLog,
  getGeneralStats,
  getGeneralCollections,
  getGeneralEntities,
} from "./client.ts";

export type { GeneralCollectionsParams, GeneralEntitiesParams } from "./client.ts";

export type {
  ApiMeta,
  ApiResponse,
  AuditLogEntry,
  AuditLogParams,
  BoardAggregates,
  BoardResponse,
  BoardRow,
  ButlerConfigResponse,
  ButlerDetail,
  ButlerMcpTool,
  ModuleStatus,
  ButlerMcpToolCallRequest,
  ButlerMcpToolCallResponse,
  ButlerSkill,
  ButlerSummary,
  ProcessFacts,
  CalendarConflictEntry,
  CalendarDedupMatchStrategy,
  CalendarDedupRulesModel,
  CalendarDedupRulesUpdateRequest,
  CalendarDuplicateCluster,
  CalendarDuplicatesParams,
  CalendarDuplicatesResponse,
  CalendarKeepSeparateRequest,
  CalendarKeepSeparateResponse,
  CalendarPrepAttendee,
  CalendarPrepNote,
  CalendarPrepResponse,
  CalendarSuggestedSlot,
  CalendarWorkspaceCapabilities,
  CalendarWorkspaceCapabilitiesSync,
  CalendarWorkspaceButlerMutationAction,
  CalendarWorkspaceButlerMutationRequest,
  CalendarWorkspaceLaneDefinition,
  CalendarWorkspaceMetaResponse,
  CalendarWorkspaceMutationResponse,
  CalendarFindTimeConstraints,
  CalendarFindTimePartOfDay,
  CalendarWorkspaceFindTimeRequest,
  CalendarWorkspaceFindTimeResponse,
  CalendarWorkspaceParams,
  CalendarWorkspaceReadResponse,
  CalendarWorkspaceSearchParams,
  CalendarWorkspaceSearchResponse,
  CalendarWorkspaceSourceFreshness,
  CalendarWorkspaceUserMutationAction,
  CalendarWorkspaceUserMutationRequest,
  CalendarWorkspaceSyncRequest,
  CalendarWorkspaceSyncResponse,
  CalendarWorkspaceSyncState,
  CalendarWorkspaceSyncTarget,
  CalendarWorkspaceView,
  CalendarWorkspaceWritableCalendar,
  SetPrimaryCalendarRequest,
  SetPrimaryCalendarResponse,
  UnifiedCalendarEntry,
  UnifiedCalendarSourceType,
  SpendSummary,
  DailySpend,
  Dose,
  DoseLogRequest,
  MedicationAdherence,
  CreateEntityInfoRequest,
  CreateEntityInfoResponse,
  EntityDetail,
  EntityInfoEntry,
  EntityParams,
  EntitySummary,
  UpdateEntityRequest,
  EntityGift,
  EntityLoan,
  EntityTimelineItem,
  LinkedContactSummary,
  ContactFact,
  AddEntityContactRequest,
  AddEntityContactResponse,
  DeleteEntityContactResponse,
  UpdateEntityContactRequest,
  UpdateEntityContactResponse,
  SetPreferredChannelRequest,
  SetPreferredChannelResponse,
  ClearPreferredChannelResponse,
  NeighbourEntry,
  NeighboursResponse,
  NeighboursParams,
  EntityFact,
  EntityFactStore,
  EntityFactStalenessBand,
  EntityFactsResponse,
  EntityFactsValidity,
  EntityFactsParams,
  ActivityBin,
  ActivityBinsResponse,
  ViewMarkResponse,
  DeltaFactStore,
  DeltaFactEntry,
  DeltaFactsResponse,
  CoreDateEntry,
  CoreDatesResponse,
  PredicateTab,
  ConcentrationEntry,
  ConcentrationRollup,
  ConcentrationResponse,
  RelationshipEntityDetail,
  RelationshipEntitySummary,
  RelationshipEntityListResponse,
  RelationshipEntityListParams,
  RelationshipQueueEntry,
  RelationshipQueueResponse,
  DismissRelationshipEntityQueueResponse,
  CompareEntitiesRequest,
  CompareEntitiesResponse,
  CompareFact,
  CompareEntityBlock,
  CompareEntitySummary,
  DismissEntityPairRequest,
  DismissEntityPairResponse,
  MergeRelationshipEntitiesRequest,
  MergeRelationshipEntitiesResponse,
  PromoteRelationshipEntityRequest,
  CreateRelationshipEntityRequest,
  Episode,
  EpisodeParams,
  ErrorDetail,
  ErrorResponse,
  HealthCondition,
  ConditionCreateRequest,
  ConditionUpdateRequest,
  HealthResearch,
  ResearchCreateRequest,
  ResearchUpdateRequest,
  Fact,
  FactParams,
  HealthAuthPosture,
  HealthResponse,
  HealthSecurityPosture,
  Issue,
  Meal,
  MealParams,
  MealCreateRequest,
  MealUpdateRequest,
  MealNutrition,
  NutritionSummaryParams,
  NutritionSummary,
  NutritionDailyAverage,
  MemoryActivity,
  CompactionLogEntry,
  MemoryInspectParams,
  MemoryInspectResult,
  MemoryRetentionPolicy,
  MemoryRule,
  MemoryStats,
  ReembedPendingCounts,
  ReembedRunRequest,
  ReembedRunResult,
  UpdateRetentionPoliciesRequest,
  UpdateRetentionPolicyEntry,
  LatestMeasurementEntry,
  Measurement,
  MeasurementParams,
  MeasurementType,
  MeasurementCreateRequest,
  MeasurementUpdateRequest,
  MeasurementSource,
  MeasurementsLatestResponse,
  MeasurementSourcesResponse,
  MeasurementTrendParams,
  MeasurementTrendBucket,
  MeasurementTrendResponse,
  InsightCandidate,
  InsightCandidatesParams,
  Medication,
  MedicationParams,
  MedicationCreateRequest,
  MedicationUpdateRequest,
  SleepLatestResponse,
  SleepStage,
  AckFailedResult,
  NotificationParams,
  NotificationStats,
  NotificationStatsParams,
  NotificationSummary,
  AttentionLedgerSummaryParams,
  AttentionLedgerSummaryResponse,
  AttentionSourceSummary,
  CursorPaginatedResponse,
  CursorPaginationMeta,
  PaginatedResponse,
  PaginationMeta,
  ResearchParams,
  RuleParams,
  RegistryEntry,
  RoutingEntry,
  SetEligibilityResponse,
  RoutingLogParams,
  Schedule,
  ScheduleCreate,
  ScheduleUpdate,
  SearchResult,
  SearchResults,
  SessionAggregate,
  SessionAggregateButler,
  SessionAggregateTriggerSource,
  SessionDetail,
  SessionParams,
  SessionSummary,
  KeysetMeta,
  KeysetResponse,
  StateEntry,
  StateSetRequest,
  Symptom,
  SymptomParams,
  SymptomCreateRequest,
  SymptomUpdateRequest,
  TimelineEvent,
  TimelineMeta,
  TimelineParams,
  TimelineResponse,
  TopSession,
  ScheduleCost,
  DispatchAttemptEntry,
  DispatchAttemptsParams,
  ContactDetail,
  ContactInfoEntry,
  ContactListResponse,
  ContactPatchRequest,
  ContactParams,
  ContactSummary,
  OwnerSetupStatus,
  TargetContact,
  Group,
  GroupListResponse,
  GroupMember,
  GroupMembersResponse,
  GroupParams,
  Label,
  TriggerResponse,
  TickResponse,
  UpcomingDate,
  ApprovalAction,
  ApprovalActionParams,
  ApprovalApproveRequest,
  ApprovalDeferRequest,
  ApprovalDenyRequest,
  ApprovalDetail,
  ApprovalGatedTool,
  ApprovalMetrics,
  ApprovalRule,
  ApprovalRuleCreateRequest,
  ApprovalRuleFromActionRequest,
  ApprovalRuleParams,
  ApprovalsListMeta,
  ApprovalsListResponse,
  ApprovalsPolicy,
  ApprovalSummary,
  AutonomySuggestion,
  AutonomySuggestionDismissRequest,
  AutonomySuggestionParams,
  AutonomySuggestionVelocity,
  RuleConstraintSuggestion,
  RulePromotionSuggestion,
  RulePromotionAutoApplied,
  RulePromotionSurface,
  RulePromotionStats,
  RulePromotionDismissRequest,
  DisconnectAccountResponse,
  GoogleAccount,
  GoogleAccountStatus,
  GoogleCredentialStatusResponse,
  GoogleHealthAccountStatus,
  GoogleHealthConnectorState,
  GoogleHealthDisconnectResponse,
  GoogleHealthStatusResponse,
  GeneralSettings,
  GeneralCollection,
  GeneralEntity,
  GeneralStats,
  GeneralSizeHistogramBucket,
  OAuthCredentialState,
  SetPrimaryAccountResponse,
  UpsertAppCredentialsRequest,
  UpsertAppCredentialsResponse,
  CLIAuthApiKeyResponse,
  CLIAuthHealthState,
  CLIAuthProvider,
  CLIAuthSessionState,
  CLIAuthStartResponse,
  CLIAuthSessionResponse,
  CLIAuthTestResponse,
} from "./types.ts";

export {
  cancelCLIAuthSession,
  deleteCLIAuthApiKey,
  getCLIAuthSession,
  listCLIAuthProviders,
  saveCLIAuthApiKey,
  startCLIAuth,
  testCLIAuthApiKey,
} from "./client.ts";

export {
} from "./client.ts";

export type {
  SecretCategory,
  SecretEntry,
  SecretTemplate,
} from "./types.ts";

export {
  listAvailableConnectors,
} from "./client.ts";

export type {
  ConnectorEntry,
  ConnectorProfile,
} from "./types.ts";

export {
} from "./client.ts";

export type {
} from "./types.ts";

export {
  archiveConnector,
  bulkRetryEvents,
  getConnectorDetail,
  getConnectorEvents,
  getConnectorIncidents,
  getConnectorRoutingRules,
  getConnectorStats,
  getConnectorSummariesWithAggregates,
  getPipelineStats,
  listConnectorSummaries,
  updateConnectorSettings,
} from "./client.ts";

export type {
  ConnectorArchiveResult,
  ConnectorCheckpoint,
  ConnectorCrossSummaryResponse,
  ConnectorCounters,
  ConnectorDaySummary,
  ConnectorDetail,
  ConnectorEventsResponse,
  ConnectorIncidentsResponse,
  ConnectorRoutingRulesResponse,
  ConnectorStats,
  ConnectorStatsBucket,
  ConnectorStatsSummary,
  ConnectorSummariesResponse,
  ConnectorSummary,
  IngestionPeriod,
  PipelineStats,
} from "./types.ts";

export {
  listIngestionEvents,
  getIngestionEvent,
  getIngestionEventSessions,
  getIngestionEventRollup,
  getIngestionWindowRollup,
  getIngestionEventsHistogram,
  replayIngestionEvent,
  getIngestionEventReplays,
  getIngestionEventSenderContact,
  getIngestionEventPayload,
} from "./client.ts";

export type {
  IngestionEventStatus,
  IngestionEventSummary,
  IngestionEventListSessionSummary,
  IngestionEventDetail,
  IngestionEventSession,
  IngestionEventRollup,
  IngestionEventReplayResponse,
  IngestionEventReplayHistoryEntry,
  IngestionEventSenderContact,
  IngestionEventPayload,
  IngestionEventsParams,
  ButlerRollupEntry,
  IngestionWindowRollup,
  IngestionWindowRollupParams,
  IngestionHistogramBucketSize,
  IngestionHistogramParams,
  IngestionHistogramCounts,
  IngestionHistogramBucket,
  IngestionHistogramResponse,
  BulkRetryEventResult,
  BulkRetryEventsResponse,
} from "./types.ts";

export {
  createIngestionRule,
  deleteIngestionRule,
  getIngestionRules,
  testIngestionRule,
  updateIngestionRule,
} from "./client.ts";

export type {
  IngestionRule,
  IngestionRuleCreate,
  IngestionRuleListParams,
  IngestionRuleTestEnvelope,
  IngestionRuleTestRequest,
  IngestionRuleTestResponse,
  IngestionRuleTestResult,
  IngestionRuleUpdate,
} from "./types.ts";

export { getChannelDefault, updateChannelDefault } from "./client.ts";

export type {
  ChannelDefaultEntry,
  ChannelDefaultPolicy,
  ChannelDefaultPriorityAction,
  ChannelDefaultUpdate,
} from "./types.ts";

export {
  addPriorityContact,
  getPriorityContacts,
  removePriorityContact,
  searchContacts,
} from "./client.ts";

export type {
  PriorityContactAddRequest,
  PriorityContactAddResponse,
  PriorityContactEntry,
  PriorityContactListParams,
  ContactMatchedIdentifier,
  ContactSearchResult,
  ContactSearchResponse,
} from "./types.ts";

export {
  fetchPricingMap,
  listModelCatalog,
  createModelCatalogEntry,
  updateModelCatalogEntry,
  testModelCatalogEntry,
  deleteModelCatalogEntry,
  listButlerModelOverrides,
  upsertButlerModelOverrides,
  deleteButlerModelOverride,
  resolveButlerModel,
  setModelTokenLimits,
  resetModelUsage,
  getModelUsageDetail,
  updateModelPriority,
  verifyAllModels,
} from "./client.ts";

export type {
  ComplexityTier,
  ModelCatalogEntry,
  ModelPricingEntry,
  PricingMap,
  ModelCatalogCreate,
  ModelCatalogUpdate,
  ModelPriorityDelta,
  VerifyAllResult,
  ModelTestResult,
  ButlerModelOverride,
  ButlerModelOverrideUpsert,
  ResolveModelResponse,
  TokenLimitsRequest,
  TokenLimitsResponse,
  ResetUsageRequest,
  TokenUsageDetail,
  UsageWindow,
} from "./types.ts";

export {
} from "./client.ts";

export type {
} from "./types.ts";

export {
} from "./client.ts";

export type {
} from "./types.ts";

export {
  disconnectWhatsApp,
  getWhatsAppStatus,
  pollWhatsAppPairing,
  startWhatsAppPairing,
} from "./client.ts";

export type {
  WhatsAppDisconnectResponse,
  WhatsAppPairPollResponse,
  WhatsAppPairStartResponse,
  WhatsAppState,
  WhatsAppStatusResponse,
} from "./types.ts";

export {
  disconnectSpotify,
  getSpotifyStatus,
  saveSpotifyConfig,
  startSpotifyOAuth,
} from "./client.ts";

export type {
  SpotifyConfigRequest,
  SpotifyConfigResponse,
  SpotifyDisconnectResponse,
  SpotifyOAuthStartResponse,
  SpotifyState,
  SpotifyStatusResponse,
} from "./types.ts";

export {
  generateOwnTracksToken,
  getOwnTracksConfig,
  getOwnTracksStatus,
} from "./client.ts";

export type {
  OwnTracksConfigResponse,
  OwnTracksState,
  OwnTracksStatusResponse,
  OwnTracksTokenResponse,
} from "./types.ts";

export {
  configureHomeAssistant,
  deleteHomeAssistantConfig,
  getHomeAssistantStatus,
} from "./client.ts";

export type {
  HomeAssistantConfigRequest,
  HomeAssistantConfigResponse,
  HomeAssistantDeleteResponse,
  HomeAssistantState,
  HomeAssistantStatusResponse,
} from "./types.ts";

export {
  getEducationCrossTopicAnalytics,
  getEducationMasterySummary,
  getEducationMindMap,
  getEducationMindMapAnalytics,
  getEducationMindMapAnalyticsTrend,
  getEducationMindMapFrontier,
  getEducationMindMaps,
  getEducationPendingReviews,
  getEducationQuizResponses,
  requestEducationCurriculum,
  updateEducationMindMapStatus,
  getDunbarRanking,
  listConversations,
  getConversationMessages,
  searchConversations,
  createConversation,
  sendMessage,
} from "./client.ts";

export type {
  AnalyticsSnapshot,
  AnalyticsSnapshotTrendEntry,
  AnalyticsTrendEntry,
  AnalyticsTrendResponse,
  CrossTopicAnalytics,
  CrossTopicEntry,
  CurriculumRequestBody,
  CurriculumRequestResponse,
  MasterySummary,
  MindMap,
  MindMapEdge,
  MindMapListParams,
  MindMapNode,
  PendingReviewNode,
  QuizResponse,
  QuizResponseParams,
  DunbarEntry,
  DunbarRankingResponse,
  ContactInteraction,
  ContactInteractionsResponse,
  OverdueContact,
  OverdueContactsResponse,
  ConversationSummary,
  ConversationListParams,
  Message,
  MessageToolCall,
  CreateConversationRequest,
  SendMessageRequest,
  ConversationSseEventType,
  ConversationSseEvent,
} from "./types.ts";

export {
  getTelegramSessionStatus,
  telegramSendCode,
  telegramVerifyCode,
} from "./client.ts";

export type {
  TelegramSendCodeRequest,
  TelegramSendCodeResponse,
  TelegramVerifyCodeRequest,
  TelegramVerifyCodeResponse,
  TelegramSessionStatusResponse,
} from "./types.ts";

export {
  connectSteamAccount,
  disconnectSteamAccount,
  listSteamAccounts,
} from "./client.ts";

export type {
  SteamAccountListResponse,
  SteamAccountResponse,
  SteamAccountStatus,
  SteamConnectRequest,
  SteamConnectResponse,
  SteamDisconnectResponse,
} from "./types.ts";

export {
  getInstanceFacts,
  getDatabaseFacts,
  getBackupFacts,
  getEgressCatalog,
  getButlerHeartbeats,
  getInsightDeliveryState,
  getDriftFacts,
  getDeploymentFacts,
} from "./client.ts";

export type {
  BackupEvent,
  BackupFacts,
  ButlerHeartbeat,
  DatabaseFacts,
  DeploymentFacts,
  DeploymentRecord,
  DriftEntry,
  DriftFacts,
  EgressActor,
  EgressCatalog,
  HeartbeatFacts,
  InsightDeliveryState,
  InstanceFacts,
  SchemaSize,
  TableSize,
} from "./types.ts";

export {
  dismissQaKnownIssue,
  forceQaPatrol,
  getQaCase,
  getQaCaseJournal,
  getQaCases,
  getQaInvestigations,
  getQaPatrol,
  getQaPatrols,
  getQaSummary,
  removeQaDismissal,
  retryHealingAttempt,
  type RetryHealingAttemptResponse,
  getQaCircuitBreaker,
  resetQaCircuitBreaker,
  getQaRepoConfig,
  updateQaRepoConfig,
  syncQaRepo,
  updateQaGitAuthor,
  getQaAllowedRepos,
  addQaAllowedRepo,
  patchQaAllowedRepo,
  deleteQaAllowedRepo,
  getRuntimeConfig,
  patchRuntimeConfig,
} from "./client.ts";

export type {
  CircuitBreakerAttempt,
  CircuitBreakerResetResponse,
  CircuitBreakerStatus,
  ForcePatrolResponse,
  QaRepoConfig,
  QaRepoConfigUpdate,
  QaRepoSyncResponse,
  QaGitAuthorUpdate,
  QaGitAuthorStatus,
  QaAllowedRepo,
  QaAllowedRepoCreate,
  QaAllowedRepoPatch,
  QaActiveBreakdown,
  QaActiveDismissal,
  QaAllTimeStats,
  QaCaseDossier,
  QaCaseJournalParams,
  QaCasesParams,
  QaCaseSummary,
  QaDismissal,
  QaDismissRequest,
  QaFindingRecord,
  QaInvestigation,
  QaInvestigationNotes,
  QaInvestigationsParams,
  QaJournalEvent,
  QaKpiBlock,
  QaKnownIssue,
  QaPatrolDetail,
  QaPatrolsParams,
  QaPatrolSummary,
  QaPrSummary,
  QaStats24h,
  QaSummary,
  RuntimeConfigResponse,
  RuntimeConfigPatch,
  RuntimeConfigPatchResponse,
} from "./types.ts";

export {
  getChroniclerAggregateByCategory,
  getChroniclerAggregateByDay,
  getChroniclerDayClose,
  getChroniclerEpisodes,
  getChroniclerSourceState,
} from "./client.ts";

export type {
  ChroniclerAggregateByCategoryParams,
  ChroniclerAggregateByDayParams,
  ChroniclerAggregateByDayRow,
  ChroniclerCategoryBucket,
  ChroniclerCategoryBuckets,
  ChroniclerDayCloseParams,
  ChroniclerDayCloseFreshResponse,
  ChroniclerDayCloseResponse,
  ChroniclerDayCloseStaleResponse,
  ChroniclerEpisode,
  ChroniclerEpisodesParams,
  ChroniclerSourceBreakdownEntry,
  ChroniclerSourceStateRow,
  ChroniclerSubsourceCheckpoint,
} from "./types.ts";

export {
  getFinanceAccounts,
  getFinanceSpendingSummary,
  getFinanceSubscriptions,
  getFinanceTransactions,
  getFinanceUpcomingBills,
  patchFinanceBulkMetadata,
} from "./client.ts";

export type {
  FinanceAccount,
  FinanceAccountListParams,
  FinanceBill,
  FinanceBulkUpdateMatch,
  FinanceBulkUpdateOp,
  FinanceBulkUpdateOpResult,
  FinanceBulkUpdateRequest,
  FinanceBulkUpdateResponse,
  FinanceBulkUpdateSet,
  FinanceSpendingGroup,
  FinanceSpendingSummary,
  FinanceSpendingSummaryParams,
  FinanceSubscription,
  FinanceSubscriptionListParams,
  FinanceTransaction,
  FinanceTransactionListParams,
  FinanceUpcomingBillItem,
  FinanceUpcomingBillsParams,
  FinanceUpcomingBillsResponse,
} from "./types.ts";

// ---------------------------------------------------------------------------
// Travel butler (bu-0eac9)
// ---------------------------------------------------------------------------

export {
  getTravelTrips,
  getTravelTripSummary,
  getTravelUpcoming,
  getTravelExpiringDocuments,
} from "./client.ts";

export type {
  TravelAccommodation,
  TravelAlert,
  TravelDocument,
  TravelExpiringDocument,
  TravelExpiringDocumentsResponse,
  TravelLeg,
  TravelPreTripAction,
  TravelReservation,
  TravelTimelineEntry,
  TravelTrip,
  TravelTripSummary,
  TravelTripsParams,
  TravelUpcomingModel,
  TravelUpcomingTrip,
} from "./types.ts";

export type {
  HomeSnapshotStatus,
  HomeDeviceEntry,
  HomeDevicePaginationMeta,
  HomeDeviceInventoryResponse,
  HomeEnergyDataPoint,
  HomeTopConsumer,
  HomeMaintenanceItem,
  HomeCommandLogEntry,
} from "./types.ts";

// ---------------------------------------------------------------------------
// Butler logs (bu-iuol4.17)
// ---------------------------------------------------------------------------

export type {
  LogLevel,
  ButlerLogLine,
  ButlerLogsParams,
  ButlerLogsResponse,
} from "./types.ts";

// ---------------------------------------------------------------------------
// Messenger butler (bu-iuol4.34)
// ---------------------------------------------------------------------------

export {
  getMessengerDeliveryStats,
  getMessengerCircuitStatus,
  getMessengerQueueDepth,
  getMessengerDeadLetters,
} from "./client.ts";

export type {
  MessengerDeliveryStats,
  MessengerDeliveryStatsParams,
  MessengerCircuitStatus,
  MessengerCircuitChannelEntry,
  MessengerQueueDepth,
  MessengerDeadLetterEntry,
  MessengerDeadLetterSummary,
  MessengerDeadLettersParams,
} from "./types.ts";

// ---------------------------------------------------------------------------
// Butler analytics (bu-iuol4.16)
// ---------------------------------------------------------------------------

export {
  getButlerHourlyActivity,
  getButlerDailyActivity,
  getButlerSessionKinds,
  getButlerLatencyStats,
  getButlerMemoryStats,
} from "./client.ts";

export type {
  HourlyActivity,
  HourlyActivityBucket,
  HourlyActivityParams,
  DailyActivity,
  DailyActivityBucket,
  DailyActivityParams,
  SessionKindItem,
  SessionKindBreakdown,
  SessionKindsParams,
  LatencyStats,
  LatencyStatsParams,
  ButlerMemoryStats,
} from "./types.ts";

// ---------------------------------------------------------------------------
// Activity feed (bu-y7lo7)
// ---------------------------------------------------------------------------

export { getButlerActivityFeed } from "./client.ts";

export type {
  ButlerActivityEvent,
  ActivityEventType,
  ActivityFeed,
  ActivityFeedParams,
} from "./types.ts";

// ---------------------------------------------------------------------------
// Phase 7 — butler management (§9.2)
// ---------------------------------------------------------------------------

export {
  getButlerPrompt,
  updateButlerPrompt,
  getButlerPromptHistory,
  getButlerTools,
  getButlerMemoryAccess,
  killButler,
} from "./client.ts";

export type {
  PromptVersion,
  PromptUpdateRequest,
  ButlerTool,
  MemoryAccess,
  KillRequest,
  KillResponse,
} from "./types.ts";

// ---------------------------------------------------------------------------
// Entity Finder (Cmd-K, bu-xfjwk)
// ---------------------------------------------------------------------------

export { searchRelationshipEntities } from "./client.ts";

export type {
  EntityFinderMatchKind,
  EntityFinderSearchResult,
  EntityFinderSearchResponse,
} from "./types.ts";

// ---------------------------------------------------------------------------
// Timeline saved views (bu-vgj88)
// ---------------------------------------------------------------------------

export {
  listTimelineSavedViews,
  createTimelineSavedView,
  updateTimelineSavedView,
  deleteTimelineSavedView,
} from "./client.ts";

export type {
  TimelineSavedViewEntry,
  TimelineSavedViewCreateRequest,
  TimelineSavedViewFilterSpec,
  TimelineSavedViewUpdateRequest,
} from "./types.ts";

// ---------------------------------------------------------------------------
// Owner Decision Desk -- Decisions lane (bu-ckkpz.2)
// ---------------------------------------------------------------------------

export { getDecisions } from "./client.ts";

export type {
  DecisionBeadSummary,
  DecisionsListMeta,
  DecisionsListResponse,
} from "./types.ts";
