/**
 * Public API surface — re-exports from client and types.
 */

export {
  ApiError,
  apiFetch,
  deleteGoogleCredentials,
  disconnectAccount,
  disconnectGoogleHealth,
  getAccountStatus,
  getGoogleAccounts,
  getGoogleCredentialStatus,
  getGoogleHealthStatus,
  getGoogleOAuthStartUrl,
  getOAuthStartUrl,
  getOAuthStatus,
  GOOGLE_HEALTH_SCOPES,
  setPrimaryAccount,
  upsertGoogleCredentials,
  createButlerSchedule,
  deleteButlerSchedule,
  getAuditLog,
  deleteButlerState,
  getButler,
  getButlerConfig,
  getButlerMcpTools,
  getButlerNotifications,
  getButlerSchedules,
  getButlerSession,
  getButlerSessions,
  getButlerSkills,
  getButlerState,
  getButlers,
  getConditions,
  getCalendarWorkspace,
  getCalendarWorkspaceMeta,
  mutateCalendarWorkspaceButlerEvent,
  mutateCalendarWorkspaceUserEvent,
  getCostSummary,
  getDailyCosts,
  createEntityInfo,
  deleteEntityInfo,
  getEntities,
  getEntity,
  getOwnerEntityInfo,
  archiveEntity,
  deleteEntity,
  mergeEntity,
  promoteEntity,
  unarchiveEntity,
  revealEntitySecret,
  setEntityLinkedContact,
  unlinkEntityContact,
  updateEntity,
  updateEntityInfo,
  getRelationshipEntity,
  getEntityLinkedContacts,
  getEntityNotes,
  getEntityInteractions,
  getEntityGifts,
  getEntityLoans,
  getEntityTimeline,
  getEntityMessageThreads,
  getEpisode,
  getEpisodes,
  getFact,
  getFacts,
  getHealth,
  getIssues,
  getMemoryActivity,
  getMemoryStats,
  getMeals,
  getMeasurements,
  getMedications,
  getMedicationDoses,
  getNotifications,
  getNotificationStats,
  getResearch,
  getRule,
  getRules,
  getRegistry,
  getRoutingLog,
  setButlerEligibility,
  getEligibilityHistory,
  getSession,
  getSessions,
  getSymptoms,
  getTimeline,
  getTopSessions,
  searchAll,
  getContact,
  getContacts,
  triggerContactsSync,
  getPendingContacts,
  revealContactSecret,
  patchContact,
  mergeContact,
  confirmContact,
  createContactInfo,
  archiveContact,
  unarchiveContact,
  deleteContact,
  deleteContactInfo,
  patchContactInfo,
  getOwnerSetupStatus,
  getUnlinkedContacts,
  getEntitySuggestions,
  linkEntity,
  createAndLinkEntity,
  getGroup,
  getGroups,
  getLabels,
  getUpcomingDates,
  setButlerState,
  toggleButlerSchedule,
  triggerButler,
  triggerButlerSchedule,
  callButlerMcpTool,
  updateButlerSchedule,
  approveAction,
  confirmAutonomySuggestion,
  createApprovalRule,
  createRuleFromAction,
  dismissAutonomySuggestion,
  expireStaleActions,
  getApprovalAction,
  getApprovalActions,
  getApprovalMetrics,
  getApprovalRule,
  getApprovalRules,
  getGeneralSettings,
  getAutonomySuggestions,
  getExecutedActions,
  getRuleSuggestions,
  rejectAction,
  retryAction,
  revokeApprovalRule,
  setPrimaryCalendar,
  syncCalendarWorkspace,
  updateGeneralSettings,
} from "./client.ts";

export type {
  ApiMeta,
  ApiResponse,
  AuditEntry,
  AuditLogParams,
  ButlerConfigResponse,
  ButlerMcpTool,
  ButlerMcpToolCallRequest,
  ButlerMcpToolCallResponse,
  ButlerSkill,
  ButlerSummary,
  CalendarWorkspaceCapabilities,
  CalendarWorkspaceCapabilitiesSync,
  CalendarWorkspaceButlerMutationAction,
  CalendarWorkspaceButlerMutationRequest,
  CalendarWorkspaceLaneDefinition,
  CalendarWorkspaceMetaResponse,
  CalendarWorkspaceMutationResponse,
  CalendarWorkspaceParams,
  CalendarWorkspaceReadResponse,
  CalendarWorkspaceSourceFreshness,
  CalendarWorkspaceUserMutationAction,
  CalendarWorkspaceUserMutationRequest,
  CalendarWorkspaceSyncRequest,
  CalendarWorkspaceSyncResponse,
  CalendarWorkspaceSyncState,
  CalendarWorkspaceSyncTarget,
  CalendarWorkspaceView,
  CalendarWorkspaceWritableCalendar,
  SetPrimaryCalendarRequest,
  SetPrimaryCalendarResponse,
  UnifiedCalendarEntry,
  UnifiedCalendarSourceType,
  CostSummary,
  DailyCost,
  Dose,
  CreateEntityInfoRequest,
  CreateEntityInfoResponse,
  EntityDetail,
  EntityInfoEntry,
  EntityParams,
  EntitySummary,
  MergeEntityResponse,
  OwnerEntityInfoResponse,
  UpdateEntityInfoRequest,
  UpdateEntityRequest,
  EntityNote,
  EntityInteraction,
  EntityGift,
  EntityLoan,
  EntityTimelineItem,
  LinkedContactSummary,
  RelationshipEntityDetail,
  Episode,
  EpisodeParams,
  ErrorDetail,
  ErrorResponse,
  HealthCondition,
  HealthResearch,
  Fact,
  FactParams,
  HealthResponse,
  Issue,
  Meal,
  MealParams,
  MemoryActivity,
  MemoryRule,
  MemoryStats,
  Measurement,
  MeasurementParams,
  Medication,
  MedicationParams,
  NotificationParams,
  NotificationStats,
  NotificationSummary,
  PaginatedResponse,
  PaginationMeta,
  ResearchParams,
  RuleParams,
  RegistryEntry,
  RoutingEntry,
  EligibilityHistoryResponse,
  EligibilitySegment,
  SetEligibilityResponse,
  RoutingLogParams,
  Schedule,
  ScheduleCreate,
  ScheduleUpdate,
  SearchParams,
  SearchResult,
  SearchResults,
  SessionDetail,
  SessionParams,
  SessionSummary,
  StateEntry,
  StateSetRequest,
  Symptom,
  SymptomParams,
  TimelineEvent,
  TimelineMeta,
  TimelineParams,
  TimelineResponse,
  TopSession,
  ContactDetail,
  ContactInfoEntry,
  ContactListResponse,
  ContactMergeRequest,
  ContactMergeResponse,
  ContactPatchRequest,
  CreateContactInfoRequest,
  CreateContactInfoResponse,
  PatchContactInfoRequest,
  ContactParams,
  ContactsSyncTriggerResponse,
  ContactSummary,
  OwnerSetupStatus,
  EntityLinkSuggestion,
  UnlinkedContactSummary,
  UnlinkedContactsResponse,
  LinkEntityRequest,
  LinkEntityResponse,
  CreateAndLinkEntityRequest,
  CreateAndLinkEntityResponse,
  TargetContact,
  Group,
  GroupListResponse,
  GroupParams,
  Label,
  TriggerResponse,
  UpcomingDate,
  ApprovalAction,
  ApprovalActionApproveRequest,
  ApprovalActionParams,
  ApprovalActionRejectRequest,
  ApprovalMetrics,
  ApprovalRule,
  ApprovalRuleCreateRequest,
  ApprovalRuleFromActionRequest,
  ApprovalRuleParams,
  AutonomySuggestion,
  AutonomySuggestionDismissRequest,
  AutonomySuggestionParams,
  AutonomySuggestionVelocity,
  ExpireStaleActionsResponse,
  RuleConstraintSuggestion,
  DeleteCredentialsResponse,
  DisconnectAccountResponse,
  GoogleAccount,
  GoogleAccountStatus,
  GoogleCredentialStatusResponse,
  GoogleHealthConnectorState,
  GoogleHealthDisconnectResponse,
  GoogleHealthStatusResponse,
  GeneralSettings,
  GeneralSettingsUpdate,
  OAuthCredentialState,
  OAuthCredentialStatus,
  OAuthStatusResponse,
  SetPrimaryAccountResponse,
  UpsertAppCredentialsRequest,
  UpsertAppCredentialsResponse,
  CLIAuthApiKeyResponse,
  CLIAuthHealthState,
  CLIAuthProvider,
  CLIAuthSessionState,
  CLIAuthStartResponse,
  CLIAuthSessionResponse,
  CLIAuthTestResponse,
} from "./types.ts";

export {
  cancelCLIAuthSession,
  deleteCLIAuthApiKey,
  getCLIAuthSession,
  listCLIAuthProviders,
  saveCLIAuthApiKey,
  startCLIAuth,
  testCLIAuthApiKey,
} from "./client.ts";

export {
  deleteSecret,
  getSecretMeta,
  listSecrets,
  revealSecret,
  upsertSecret,
} from "./client.ts";

export type {
  SecretCategory,
  SecretEntry,
  SecretTemplate,
  SecretUpsertRequest,
} from "./types.ts";

export {
  cancelBackfillJob,
  createBackfillJob,
  getBackfillJob,
  getBackfillJobProgress,
  listBackfillJobs,
  listConnectors,
  pauseBackfillJob,
  resumeBackfillJob,
} from "./client.ts";

export type {
  BackfillJobEntry,
  BackfillJobParams,
  BackfillJobStatus,
  BackfillJobSummary,
  BackfillLifecycleResponse,
  ConnectorEntry,
  CreateBackfillJobRequest,
} from "./types.ts";

export {
  deleteThreadAffinityOverride,
  getThreadAffinitySettings,
  listThreadAffinityOverrides,
  updateThreadAffinitySettings,
  upsertThreadAffinityOverride,
} from "./client.ts";

export type {
  ThreadAffinitySettings,
  ThreadAffinitySettingsUpdate,
  ThreadOverrideEntry,
  ThreadOverrideUpsert,
} from "./types.ts";

export {
  deleteConnector,
  getCrossConnectorSummary,
  getConnectorDetail,
  getConnectorFanout,
  getConnectorStats,
  getIngestionOverview,
  getIngestionVolume,
  listConnectorSummaries,
  updateConnectorCursor,
  updateConnectorSettings,
} from "./client.ts";

export type {
  ConnectorCheckpoint,
  ConnectorCounters,
  ConnectorDaySummary,
  ConnectorDetail,
  ConnectorFanout,
  ConnectorFanoutEntry,
  ConnectorStats,
  ConnectorStatsBucket,
  ConnectorStatsSummary,
  ConnectorSummary,
  ConnectorSummaryEntry,
  CrossConnectorSummary,
  IngestionOverviewStats,
  IngestionPeriod,
} from "./types.ts";

export {
  listIngestionEvents,
  getIngestionEvent,
  getIngestionEventSessions,
  getIngestionEventRollup,
  replayIngestionEvent,
} from "./client.ts";

export type {
  IngestionEventStatus,
  IngestionEventSummary,
  IngestionEventSession,
  IngestionEventRollup,
  IngestionEventReplayResponse,
  IngestionEventsParams,
  ButlerRollupEntry,
} from "./types.ts";

export {
  createIngestionRule,
  deleteIngestionRule,
  getIngestionRules,
  testIngestionRule,
  updateIngestionRule,
} from "./client.ts";

export type {
  IngestionRule,
  IngestionRuleCreate,
  IngestionRuleListParams,
  IngestionRuleTestEnvelope,
  IngestionRuleTestRequest,
  IngestionRuleTestResponse,
  IngestionRuleTestResult,
  IngestionRuleUpdate,
} from "./types.ts";

export {
  fetchPricingMap,
  listModelCatalog,
  createModelCatalogEntry,
  updateModelCatalogEntry,
  testModelCatalogEntry,
  deleteModelCatalogEntry,
  listButlerModelOverrides,
  upsertButlerModelOverrides,
  deleteButlerModelOverride,
  resolveButlerModel,
  setModelTokenLimits,
  resetModelUsage,
  getModelUsageDetail,
} from "./client.ts";

export type {
  ComplexityTier,
  ModelCatalogEntry,
  ModelPricingEntry,
  PricingMap,
  ModelCatalogCreate,
  ModelCatalogUpdate,
  ModelTestResult,
  ButlerModelOverride,
  ButlerModelOverrideUpsert,
  ResolveModelResponse,
  TokenLimitsRequest,
  TokenLimitsResponse,
  ResetUsageRequest,
  TokenUsageDetail,
  UsageWindow,
} from "./types.ts";

export {
  listProviders,
  createProvider,
  updateProvider,
  deleteProvider,
  testProviderConnectivity,
} from "./client.ts";

export type {
  ProviderConfig,
  ProviderConfigCreate,
  ProviderConfigUpdate,
  ProviderConnectivityResult,
} from "./types.ts";

export {
  getBlobStorageStatus,
  testBlobStorage,
} from "./client.ts";

export type {
  BlobStorageStatus,
  BlobStorageTestResult,
} from "./types.ts";

export {
  disconnectWhatsApp,
  getWhatsAppHealth,
  getWhatsAppStatus,
  pollWhatsAppPairing,
  startWhatsAppPairing,
} from "./client.ts";

export type {
  WhatsAppDisconnectResponse,
  WhatsAppHealthResponse,
  WhatsAppPairPollResponse,
  WhatsAppPairStartResponse,
  WhatsAppState,
  WhatsAppStatusResponse,
} from "./types.ts";

export {
  disconnectSpotify,
  getSpotifyStatus,
  saveSpotifyConfig,
  startSpotifyOAuth,
} from "./client.ts";

export type {
  SpotifyConfigRequest,
  SpotifyConfigResponse,
  SpotifyDisconnectResponse,
  SpotifyOAuthStartResponse,
  SpotifyState,
  SpotifyStatusResponse,
} from "./types.ts";

export {
  generateOwnTracksToken,
  getOwnTracksConfig,
  getOwnTracksStatus,
} from "./client.ts";

export type {
  OwnTracksConfigResponse,
  OwnTracksState,
  OwnTracksStatusResponse,
  OwnTracksTokenResponse,
} from "./types.ts";

export {
  configureHomeAssistant,
  deleteHomeAssistantConfig,
  getHomeAssistantStatus,
} from "./client.ts";

export type {
  HomeAssistantConfigRequest,
  HomeAssistantConfigResponse,
  HomeAssistantDeleteResponse,
  HomeAssistantState,
  HomeAssistantStatusResponse,
} from "./types.ts";

export {
  getEducationCrossTopicAnalytics,
  getEducationFlows,
  getEducationMasterySummary,
  getEducationMindMap,
  getEducationMindMapAnalytics,
  getEducationMindMapFrontier,
  getEducationMindMaps,
  getEducationPendingReviews,
  getEducationQuizResponses,
  requestEducationCurriculum,
  updateEducationMindMapStatus,
  getDunbarRanking,
  listConversations,
  getConversation,
  getConversationMessages,
  searchConversations,
  createConversation,
  sendMessage,
} from "./client.ts";

export type {
  AnalyticsSnapshot,
  AnalyticsSnapshotTrendEntry,
  CrossTopicAnalytics,
  CrossTopicEntry,
  CurriculumRequestBody,
  CurriculumRequestResponse,
  MasterySummary,
  MindMap,
  MindMapEdge,
  MindMapListParams,
  MindMapNode,
  PendingReviewNode,
  QuizResponse,
  QuizResponseParams,
  TeachingFlow,
  DunbarEntry,
  DunbarRankingResponse,
  ConversationSummary,
  ConversationListParams,
  Message,
  MessageToolCall,
  CreateConversationRequest,
  SendMessageRequest,
  ConversationSseEventType,
  ConversationSseEvent,
} from "./types.ts";

export {
  getTelegramSessionStatus,
  telegramSendCode,
  telegramVerifyCode,
} from "./client.ts";

export type {
  TelegramSendCodeRequest,
  TelegramSendCodeResponse,
  TelegramVerifyCodeRequest,
  TelegramVerifyCodeResponse,
  TelegramSessionStatusResponse,
} from "./types.ts";

export {
  connectSteamAccount,
  disconnectSteamAccount,
  getSteamPlaytime,
  listSteamAccounts,
} from "./client.ts";

export type {
  SteamAccountListResponse,
  SteamAccountResponse,
  SteamAccountStatus,
  SteamConnectRequest,
  SteamConnectResponse,
  SteamDisconnectResponse,
  SteamGamePlaytime,
  SteamPlaytimeAnalytics,
} from "./types.ts";

export {
  dismissQaKnownIssue,
  forceQaPatrol,
  getQaFindingByAttempt,
  getQaInvestigations,
  getQaKnownIssues,
  getQaPatrol,
  getQaPatrolFindings,
  getQaPatrols,
  getQaSummary,
  getQaTrends,
  undismissQaKnownIssue,
  getHealingAttempt,
  listHealingAttempts,
  getQaCircuitBreaker,
  resetQaCircuitBreaker,
  getQaRepoConfig,
  updateQaRepoConfig,
  syncQaRepo,
  getQaAllowedRepos,
  addQaAllowedRepo,
  patchQaAllowedRepo,
  deleteQaAllowedRepo,
  getRuntimeConfig,
  patchRuntimeConfig,
} from "./client.ts";

export type {
  CircuitBreakerAttempt,
  CircuitBreakerResetResponse,
  CircuitBreakerStatus,
  ForcePatrolResponse,
  QaRepoConfig,
  QaRepoConfigUpdate,
  QaRepoSyncResponse,
  QaAllowedRepo,
  QaAllowedRepoCreate,
  QaAllowedRepoPatch,
  QaAllTimeStats,
  QaDismissal,
  QaDismissRequest,
  QaFindingRecord,
  QaInvestigation,
  QaInvestigationsParams,
  QaKnownIssue,
  QaKnownIssuesParams,
  QaPatrolDetail,
  QaPatrolsParams,
  QaPatrolSummary,
  QaSourceBreakdown,
  QaStats24h,
  QaSummary,
  QaTrends,
  QaTrendsDay,
  HealingAttempt,
  HealingAttemptsParams,
  RuntimeConfigResponse,
  RuntimeConfigPatch,
  RuntimeConfigPatchResponse,
} from "./types.ts";

export {
  getChroniclerAggregateByCategory,
  getChroniclerAggregateByDay,
  getChroniclerDayClose,
  getChroniclerEpisodes,
  getChroniclerSourceState,
} from "./client.ts";

export type {
  ChroniclerAggregateByCategoryParams,
  ChroniclerAggregateByDayParams,
  ChroniclerAggregateByDayRow,
  ChroniclerCategoryBucket,
  ChroniclerCategoryBuckets,
  ChroniclerDayCloseParams,
  ChroniclerDayCloseFreshResponse,
  ChroniclerDayCloseResponse,
  ChroniclerDayCloseStaleResponse,
  ChroniclerEpisode,
  ChroniclerEpisodesParams,
  ChroniclerSourceBreakdownEntry,
  ChroniclerSourceStateRow,
  ChroniclerSubsourceCheckpoint,
} from "./types.ts";
