"""runtime_probe_control_receipts: fence the table owner too.

Revision ID: core_212
Revises: core_211
Create Date: 2026-09-04 00:00:00.000000

REQ-database-security-008.  core_201 deliberately left this table's row
security ENABLEd but not FORCEd, because FORCE would also fence the table
OWNER -- the shared migration/dashboard login -- and that is exactly the
identity ``deploy/backup/pg_dump.sh`` dumps as.

That reasoning undersold a second fact: the Dashboard API pool also connects
as that same owner identity (``src/butlers/api/deps.py`` disables ``SET
ROLE`` for every API-managed pool -- schema isolation is enforced at the
butler-daemon layer, not the API layer), so the owner is not just a backup
concern.  It is the principal the Dashboard itself queries through, and
``ENABLE`` without ``FORCE`` exempts exactly that principal from the policy
that is supposed to gate this table to ``butler_switchboard_rw`` alone.

This revision closes that gap the same way the codebase already closes it
for every other RLS table the dump role cannot read: ``FORCE`` the policy, and
add the table's qualified name to ``deploy/backup/pg_dump.sh``'s
``BACKUP_EXCLUDE_TABLES`` (see that script's header and
``tests/scripts/test_pg_dump_backup.py::test_exclusion_set_matches_the_fenced_objects_exactly``,
which now discovers this table as fenced and would fail the nightly dump
build if the script were not updated to match).  Excluding it costs nothing a
restore needs: a receipt has no meaning once its 5-second retention skew
lapses, and every live receipt is regenerated by the next capability use, the
same "expiring, self-regenerating" shape ``public.expected_signals`` and
``public.user_context`` already have in that exclusion list.

A second, unrelated gap: ``TRUNCATE`` does not fire the ``FOR EACH ROW``
retention trigger core_201 installed (Postgres never fires row-level triggers
for a statement that produces no rows), and RLS policies do not gate
``TRUNCATE`` at all -- forcing row security does not touch this.  The owner
also cannot be stripped of the implicit ``TRUNCATE`` right that PostgreSQL
grants to every table owner; ``REVOKE`` has no effect on it.  The guard has to
be a trigger, not a grant: a ``BEFORE TRUNCATE ... FOR EACH STATEMENT``
trigger fires for every principal, owner included, so an unconditional raise
here closes the reopen-the-replay-window path TRUNCATE would otherwise leave
open.
"""

from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "core_212"
down_revision = "core_211"
branch_labels = None
depends_on = None

_RECEIPTS = "public.runtime_probe_control_receipts"
_NO_TRUNCATE_FUNCTION = "public.runtime_probe_control_receipts_no_truncate"


def upgrade() -> None:
    # Row security now applies to the table owner too, closing the exemption
    # ENABLE alone leaves open.  See deploy/backup/pg_dump.sh for the matching
    # backup-exclusion update this requires.
    op.execute(f"ALTER TABLE {_RECEIPTS} FORCE ROW LEVEL SECURITY")

    # TRUNCATE has no row-level shape for the existing retention trigger to
    # catch, and RLS never gates TRUNCATE at all -- so this is a second,
    # independent guard, not a consequence of FORCE above.
    op.execute(f"""
        CREATE OR REPLACE FUNCTION {_NO_TRUNCATE_FUNCTION}()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $$
        BEGIN
            RAISE EXCEPTION
                'runtime-probe control receipts cannot be truncated; '
                'purge_expired() is the only supported retention path';
        END
        $$;
    """)
    op.execute(
        f"DROP TRIGGER IF EXISTS trg_runtime_probe_control_receipts_no_truncate ON {_RECEIPTS}"
    )
    op.execute(f"""
        CREATE TRIGGER trg_runtime_probe_control_receipts_no_truncate
            BEFORE TRUNCATE ON {_RECEIPTS}
            FOR EACH STATEMENT
            EXECUTE FUNCTION {_NO_TRUNCATE_FUNCTION}()
    """)


def downgrade() -> None:
    op.execute(
        f"DROP TRIGGER IF EXISTS trg_runtime_probe_control_receipts_no_truncate ON {_RECEIPTS}"
    )
    op.execute(f"DROP FUNCTION IF EXISTS {_NO_TRUNCATE_FUNCTION}()")
    op.execute(f"ALTER TABLE {_RECEIPTS} NO FORCE ROW LEVEL SECURITY")
