"""Correct-route tool — re-dispatch a misrouted ingestion event.

This module implements the ``correct_route`` MCP tool for the Switchboard butler.
It allows callers to re-dispatch a previously ingested message to the correct
butler when the original routing was wrong (misroute correction).

Key behaviors:
- Looks up the original ingestion event by ``request_id`` from ``shared.ingestion_events``
- Validates that the event is within the 1-month retention window
- Calls ``route()`` to dispatch to the correct butler, preserving original context
  and embedding a ``correction_id`` in the routing args
- Updates the original ``message_inbox`` lifecycle record to ``'corrected'``
- Records the correction in the operator audit log

Design notes:
- The 1-month retention window matches the ``message_inbox`` partition scheme,
  which means ingestion events older than 1 month may no longer have a live
  ``message_inbox`` row even if the ``shared.ingestion_events`` entry exists.
- On expiry the original raw_payload is no longer accessible, so re-dispatch is
  refused with an informative error rather than attempting a partial re-dispatch.
- The ``correction_id`` is a caller-supplied UUID that the misroute handler
  (in the source butler's ``correct`` tool) generates and passes to this function.
  It is embedded in the routing args so the target butler can record provenance.
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime, timedelta
from typing import Any
from uuid import UUID

import asyncpg

from butlers.tools.switchboard.routing.route import route as _route_tool

logger = logging.getLogger(__name__)

# Ingestion events older than this threshold are considered expired.
# The message_inbox partition scheme retains rows for 1 calendar month;
# after that the raw payload is gone and re-dispatch is not safe.
_RETENTION_WINDOW = timedelta(days=31)


async def correct_route(
    pool: asyncpg.Pool,
    *,
    request_id: str | UUID,
    correct_butler: str,
    correction_id: str | UUID,
    correcting_session_id: str | UUID | None = None,
    description: str = "",
    call_fn: Any | None = None,
) -> dict[str, Any]:
    """Re-dispatch a misrouted ingestion event to the correct butler.

    Looks up the original ingestion event by ``request_id``, validates it is
    within the 1-month retention window, and re-dispatches it to
    ``correct_butler`` via :func:`route`, augmenting the args with a
    ``correction_id`` for downstream provenance tracking.  After a successful
    dispatch the original ``message_inbox`` row is marked as ``'corrected'``.

    Parameters
    ----------
    pool:
        Database connection pool.
    request_id:
        UUID of the original ingestion event / message_inbox row to correct.
    correct_butler:
        Name of the butler that *should* have received this message.
    correction_id:
        UUID generated by the calling butler's correction handler; embedded in
        routing args so the receiving butler can record correction provenance.
    correcting_session_id:
        UUID of the session performing the correction (for audit trail). Optional.
    description:
        Human-readable description of why the message was misrouted. Optional.
    call_fn:
        Optional MCP call override for testing (forwarded to :func:`route`).

    Returns
    -------
    dict
        ``{"success": True, "new_request_id": "<uuid>", ...}`` on success, or
        ``{"success": False, "error": "<code>", "message": "<human text>"}``
        on failure.
    """
    if isinstance(request_id, str):
        request_id = UUID(request_id)
    if isinstance(correction_id, str):
        correction_id = UUID(correction_id)
    if isinstance(correcting_session_id, str):
        correcting_session_id = UUID(correcting_session_id)

    # 1. Look up the original ingestion event from shared.ingestion_events
    event_row = await pool.fetchrow(
        """
        SELECT
            id,
            received_at,
            source_channel,
            source_provider,
            source_endpoint_identity,
            source_sender_identity,
            source_thread_identity,
            external_event_id,
            dedupe_key,
            ingestion_tier,
            policy_tier,
            triage_decision,
            triage_target
        FROM shared.ingestion_events
        WHERE id = $1
        """,
        request_id,
    )

    if event_row is None:
        logger.warning("correct_route: ingestion event not found: request_id=%s", request_id)
        return {
            "success": False,
            "error": "ingestion_event_not_found",
            "message": (
                f"No ingestion event found with request_id={request_id}. "
                "Verify the request_id is correct. Use the ingestion events API to "
                "look up the original request."
            ),
        }

    # 2. Check retention window — events older than 1 month are expired
    received_at: datetime = event_row["received_at"]
    # Make timezone-aware if needed
    if received_at.tzinfo is None:
        received_at = received_at.replace(tzinfo=UTC)

    age = datetime.now(UTC) - received_at
    if age > _RETENTION_WINDOW:
        logger.warning(
            "correct_route: ingestion event expired: request_id=%s, received_at=%s, age=%s",
            request_id,
            received_at.isoformat(),
            age,
        )
        return {
            "success": False,
            "error": "ingestion_event_expired",
            "message": (
                f"Ingestion event {request_id} is {age.days} days old and has "
                "exceeded the 1-month retention window. The original message payload "
                "is no longer available for re-dispatch. "
                "For older corrections, update the target butler's state manually "
                "using the data_correction correction type instead."
            ),
        }

    # 3. Retrieve the original message_inbox row for the raw payload
    inbox_row = await pool.fetchrow(
        """
        SELECT
            id,
            received_at,
            raw_payload,
            normalized_text,
            lifecycle_state,
            request_context,
            attachments
        FROM message_inbox
        WHERE id = $1
        """,
        request_id,
    )

    if inbox_row is None:
        logger.warning(
            "correct_route: message_inbox row not found (may have been pruned): request_id=%s",
            request_id,
        )
        return {
            "success": False,
            "error": "message_inbox_not_found",
            "message": (
                f"Original message_inbox record not found for request_id={request_id}. "
                "The record may have been pruned. Use data_correction instead to "
                "correct state in the target butler directly."
            ),
        }

    # 4. Build routing args from the original ingestion context
    raw_payload_str = inbox_row["raw_payload"]
    raw_payload: dict[str, Any] = (
        json.loads(raw_payload_str) if isinstance(raw_payload_str, str) else raw_payload_str
    ) or {}

    request_context_str = inbox_row["request_context"]
    request_context: dict[str, Any] = (
        json.loads(request_context_str)
        if isinstance(request_context_str, str)
        else request_context_str
    ) or {}

    # Build route args: embed the original request context plus correction metadata.
    # The tool to call on the target butler is the standard trigger/dispatch entrypoint.
    route_args: dict[str, Any] = {
        "source_channel": event_row["source_channel"],
        "source_endpoint_identity": event_row["source_endpoint_identity"],
        "source_sender_identity": event_row["source_sender_identity"],
        "external_event_id": event_row["external_event_id"],
        "normalized_text": inbox_row["normalized_text"],
        "original_request_id": str(request_id),
        "correction_id": str(correction_id),
        "correction_type": "misroute",
    }
    if description:
        route_args["correction_description"] = description
    if correcting_session_id:
        route_args["correcting_session_id"] = str(correcting_session_id)
    if event_row["source_thread_identity"]:
        route_args["source_thread_identity"] = event_row["source_thread_identity"]
    if raw_payload:
        route_args["raw_payload"] = raw_payload

    # Preserve the original request context for full provenance
    route_args["__switchboard_route_context"] = {
        "request_id": str(request_id),
        "fanout_mode": "ordered",
        "segment_id": f"correction-{correction_id}",
        "attempt": 1,
        "correction_id": str(correction_id),
        "original_triage_decision": request_context.get("triage_decision"),
        "original_triage_target": request_context.get("triage_target"),
    }

    # 5. Route to the correct butler
    logger.info(
        "correct_route: re-dispatching request_id=%s to butler=%s, correction_id=%s",
        request_id,
        correct_butler,
        correction_id,
    )
    route_result = await _route_tool(
        pool,
        correct_butler,
        "trigger",
        route_args,
        source_butler="switchboard",
        call_fn=call_fn,
    )

    if "error" in route_result:
        logger.error(
            "correct_route: routing to %s failed: %s", correct_butler, route_result["error"]
        )
        return {
            "success": False,
            "error": "dispatch_failed",
            "message": (
                f"Failed to dispatch to butler '{correct_butler}': {route_result['error']}. "
                "Verify the butler is registered and operational via list_butlers()."
            ),
        }

    # 6. Update the original message_inbox record to reflect the correction
    correction_metadata: dict[str, Any] = {
        "correction_id": str(correction_id),
        "correction_type": "misroute",
        "correct_butler": correct_butler,
        "corrected_at": datetime.now(UTC).isoformat(),
    }
    if description:
        correction_metadata["description"] = description
    if correcting_session_id:
        correction_metadata["correcting_session_id"] = str(correcting_session_id)

    # Merge correction metadata into processing_metadata
    updated_processing_metadata: dict[str, Any] = {"correction": correction_metadata}

    await pool.execute(
        """
        UPDATE message_inbox
        SET
            lifecycle_state = 'corrected',
            processing_metadata = processing_metadata || $1::jsonb,
            updated_at = now()
        WHERE id = $2
        """,
        json.dumps(updated_processing_metadata),
        request_id,
    )

    # 7. Record in operator_audit_log for traceability
    await pool.execute(
        """
        INSERT INTO operator_audit_log (
            action_type,
            target_request_id,
            target_table,
            operator_identity,
            reason,
            action_payload,
            outcome,
            outcome_details
        )
        VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7, $8::jsonb)
        """,
        "correct_route",
        request_id,
        "message_inbox",
        f"correction:{correction_id}",
        description or "misroute correction",
        json.dumps(
            {
                "correction_id": str(correction_id),
                "correct_butler": correct_butler,
                "original_triage_target": request_context.get("triage_target"),
            }
        ),
        "success",
        json.dumps(
            {
                "lifecycle_state": "corrected",
                "correct_butler": correct_butler,
            }
        ),
    )

    logger.info(
        "correct_route: successfully re-dispatched request_id=%s to butler=%s, correction_id=%s",
        request_id,
        correct_butler,
        correction_id,
    )

    return {
        "success": True,
        "request_id": str(request_id),
        "correction_id": str(correction_id),
        "correct_butler": correct_butler,
        "lifecycle_state": "corrected",
    }
